"""empty message

Revision ID: c7bc8cbac7f1
Revises: 
Create Date: 2025-03-13 02:16:36.776915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bc8cbac7f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointment_appointment_time'), ['appointment_time'], unique=False)
        batch_op.create_unique_constraint(None, ['room_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_appointment_appointment_time'))
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
